models:
  - type: main
    engine: openai
    model: deepseek-chat
    parameters:
      base_url: "https://api.deepseek.com/v1"
    
  - type: embeddings
    engine: SentenceTransformers
    model: NeuML/bioclinical-modernbert-base-embeddings
